### PR TITLE
Add data processing steps

### PR DESCRIPTION
**Pull request by HMkrtich**
Dear group mates either read the top of pipeline.py or read the following.

I created an easier way to add your datasets to happiness data. I don't know what processing techniques you have used, so I decided to wait for you. 
The best option is for you to send me the CSV of your final versions, and I will add them quickly.

### CODE REVIEW

**Comment by akumm2k** [comment]
I think you can run the notebook for each dataset, and it will store the csvs in some cache folder automatically.
You can get the tables from there.
Meanwhile, I will prepare the dataframe regardless.
Please let us know what form you want the dataframe in.
For example,
1. Do you want the data from multiple years to be concatenated? If so, how many years?
2. Following 1, do we have any limitations on the number of rows in the dataframe? I assume you want to concatenate columns from different datasets into a bigger dataset.

**Comment by HMkrtich** [comment]
My logic is that we should concatenate everything with the happiness dataset as the labels are there (by doing left join). The thing is that we need to match with country names. Then after that, we can extend the dataset in a way we want.

**Comment by HMkrtich** [comment]
Hey everybody,
New updates: 

1. How is train/val/test split done? It is done proportionally from each region so we won't have a bias in the data. 
2. What are new datasets? I added 4 different datasets (4 different ways of generating data for later comparison)
3. What about combining datas from different years? Well we can. BUT the original data has 137 countries, however other datasets have less (most cases twice less or more) which means lots of null values. So, if we combine different years the number of null values will increase and be a big problem. Still we can try to combine datasets that more or less have the same number of countries.
What do you think?

**Comment by akumm2k** [comment]
1. Some datasets do not have region info. I couldn't find the code where you are matching the countries from said datasets to the correct regions. Could you please point me to it?
2. Let's discuss these methods briefly tomorrow. Also, how are we using the test and validation data? Currently, they seem unused. I assume the happiness index predictor would be trained on a split from the synthetic dataset.
3. So, the preferred strategy is to combine datasets with more or less the same number of countries? What do you think about using regressors to fill up the null values?

**Review by katushk-a — APPROVED** [review]

**Pull request merged**
